GUI fixes
vrc-get/vrc-get pull request #676
Opened 2024-03-28 10:04 UTC by anatawa12

Fixes #617
Fixes #622
Fixes #623
Fixes #638
Fixes #640
Fixes #647
Fixes #646
Fixes #644
Fixes #670
Fixes #650
Fixes #652
Fixes #669
Fixes #645
Fixes #639
Fixes #642
Fixes #681

2024-03-28 14:40 UTC, anatawa12 commented
<img width="1525" alt="image" src="https://github.com/vrc-get/vrc-get/assets/22656849/78d66823-fd3b-4597-935a-c99b4eb875ae">

2024-03-28 14:42 UTC, anatawa12 commented on vrc-get-gui/lib/i18n.ts
> +				'code',
note: 使いたいタグは原則ここに追加すれば良い

2024-03-28 15:15 UTC, Sayamame-beans commented
これどうやってレビューしたら良いんだろう…
checkoutしてtauri devですかね

2024-03-28 15:23 UTC, anatawa12 commented
主に見てもらいたいのはローカライズ周りだけどほかも見ていただけるなら checkout + tauri devか、ciのつくったexeで動作確認ですかね。(私はciが作ったexeでwinの動作確認はしてます)

2024-03-28 15:33 UTC, Sayamame-beans commented
638/650、文字の折り返し方がちょっと気になりますね…でも要素が分かれたりしてて対応が難しそうな予感もします
![image](https://github.com/vrc-get/vrc-get/assets/61457993/0d5bd863-0b1f-499b-bee3-24e71914c84a)

2024-03-28 15:35 UTC, Sayamame-beans commented
あとパッケージ名前後の空白が尊重されなくなってしまってますね…

2024-03-28 15:46 UTC, Sayamame-beans commented
#646 not fixed
![image](https://github.com/vrc-get/vrc-get/assets/61457993/8ba812bb-3638-423c-bfaf-643fbd168e7c)

2024-03-28 15:47 UTC, anatawa12 commented
#646 は勘違いしてました

2024-03-28 15:48 UTC, Sayamame-beans commented
#647 not fixed
ついでに、新規プロジェクト作成でも同じようになりました(下が新規、上が既存追加)
![image](https://github.com/vrc-get/vrc-get/assets/61457993/0618f4ed-ccca-4083-9767-07c7c3c353bf)

2024-03-28 15:50 UTC, Sayamame-beans commented
(恐らく647の影響で、644が継続して起きてます。647直したら直るんじゃないかな…?)

2024-03-28 15:51 UTC, anatawa12 commented
> (恐らく647の影響で、644が継続して起きてます。647直したら直るんじゃないかな…?)

多分そうだけど'/'と'\'が混ざってるのをちゃんとeqで処理するべきなのでそれ直します

2024-03-28 15:57 UTC, Sayamame-beans commented
バグ踏みました(多分このPR以前からあります)

プロジェクト作成時、末尾に空白を入れたまま作成を行えます。
ただし、少なくともwinにおいては、プロジェクトを作成しようとして末尾に空白のないフォルダが生成されるようで、vrc-get-guiは末尾に空白のある状態のフォルダを探そうとするので`io error: 指定されたパスが見つかりません。 (os error 3)`します。

2024-03-28 16:07 UTC, anatawa12 commented
> この挙動(not found系が表示される)は意図的ですか?

ある程度はい。

2024-03-28 16:08 UTC, Sayamame-beans commented on vrc-get-gui/app/repositories/page.tsx
> +				<Typography>{tc("packages: ")}</Typography>
```suggestion
				<Typography>{tc("packages:")}</Typography>
```
こっちにだけ空白が入ってて、恐らくこれが理由でこの部分のlocalesが機能してないです
逆に向こうに空白入れるべきという可能性はあります

2024-03-28 16:13 UTC, Sayamame-beans commented
### ✅ OK
617
622
623
640
670
652
669
639: 未検証

### 🛑 not OK
638/650: 言及済み
647/646: 未修正 (言及済み)
644: 未修正 (言及済み)
645: "{filename} not found"か何かでi18nしないといけなさそう
642: コメント済み

2024-03-28 16:15 UTC, anatawa12 commented
Packages folder not foundに関しては内部からなので翻訳は現状できない感じです

2024-03-29 05:22 UTC, Sayamame-beans commented on vrc-get-gui/lib/shellOpen.ts
>  	// since @tauri-apps/api uses navigator while importing, we need to import it in a function to avoid unexpected SSR
コメントがfalsyになってそう

2024-03-29 05:27 UTC, Sayamame-beans commented
確認出来る段階になったら再度review request投げてくれると助かります
既に大丈夫そうだったところは多分確認しないので、影響ありそうな箇所あれば明示してくれると助かります

2024-03-29 05:49 UTC, Sayamame-beans requested changes
review for changelog

2024-03-29 05:49 UTC, Sayamame-beans commented on CHANGELOG-gui.md
> +- Deleting a project folder moves the project folder to trach instead of hard deleting `#676`
```suggestion
- Deleting a project now moves its folder to trash instead of hard deleting `#676`
```

2024-03-29 05:49 UTC, Sayamame-beans commented on CHANGELOG-gui.md
> +- Remove button on the manage project page is not working `#676`
```suggestion
- Remove project button on the manage project page is not working `#676`
```

2024-03-29 05:49 UTC, Sayamame-beans commented on CHANGELOG.md
> +  - For resolving dependencies of packages, prerelease is used if the dependant package is prerelease, and matching version is not found without prereleases.
```suggestion
  - For resolving dependencies of packages, prerelease is used if the dependant package is prerelease, or is not but matching version is not found without prereleases.
```
ということです…?
その前提でもう一案
```suggestion
  - For resolving dependencies of packages, prerelease is used if the dependant package is prerelease, or is not but matching version is only contained in prereleases.
```

2024-03-29 05:49 UTC, Sayamame-beans commented on CHANGELOG.md
> +  - This does not change behavior with `--prerelease` option
```suggestion
  - This does not change behavior of `--prerelease` option
```
prerelease optionの動作を変えないという意図…? それともprerelease optionを使っても動作が変わらないという意図?
前者ならこの案、後者なら原案な気がします。

2024-03-29 05:54 UTC, anatawa12 commented on CHANGELOG.md
> +  - This does not change behavior with `--prerelease` option
"`--prerelease`オプションを使っているときの動作が変わらない"です

2024-03-29 05:55 UTC, anatawa12 commented on CHANGELOG.md
> +  - For resolving dependencies of packages, prerelease is used if the dependant package is prerelease, and matching version is not found without prereleases.
"package is prerelease"かつ"matching version is not found without prereleases"とき、"prerelease"が検索されます

2024-03-29 05:59 UTC, anatawa12 commented on vrc-get-gui/lib/shellOpen.ts
>  	// since @tauri-apps/api uses navigator while importing, we need to import it in a function to avoid unexpected SSR
たしかに。消します

```suggestion
```

2024-03-29 06:09 UTC, Sayamame-beans commented on CHANGELOG.md
> +  - For resolving dependencies of packages, prerelease is used if the dependant package is prerelease, and matching version is not found without prereleases.
なるほど。とすると、そのままか
```suggestion
  - For resolving dependencies of packages, prerelease is used if the dependant package is prerelease, and matching version is only contained in prereleases.
```

2024-03-29 06:57 UTC, Sayamame-beans requested changes

2024-03-29 06:57 UTC, Sayamame-beans commented on CHANGELOG.md
> +  - This does not change behavior of `--prerelease` option
```suggestion
  - This does not change behavior of `--prerelease` option.
```
抜けてた(そもそも一貫性があるわけではないようですが、ここには何となく欲しいと思いました)

2024-03-29 06:57 UTC, Sayamame-beans commented on CHANGELOG.md
> +  - For resolving dependencies of packages, prerelease is used if the dependant package is prerelease, and matching version is only contained in prereleases.
コンマがあると独立して見える感じ(ifに繋がってない感じ)がしてきたので外します。(1節が長くなってるのが欠点)
ifじゃなくてwhenとかにした方がわかりやすいんですかね…(悩む)
あと、なんとなくtheを足してみます。
```suggestion
  - For resolving dependencies of packages, prerelease is used if the dependant package is prerelease and the matching version is only contained in prereleases.
```

2024-03-29 07:07 UTC, Sayamame-beans commented on CHANGELOG.md
> +  - For resolving dependencies of packages, prerelease is used if the dependant package is prerelease, and matching version is only contained in prereleases.
本質はFor～から始まってコンマが使われてることで、ifの中でコンマを使うと途切れて見えることなので、when使っても別に変わらないな…

2024-03-29 07:27 UTC, Sayamame-beans commented
> #638 / #650、文字の折り返し方がちょっと気になりますね…でも要素が分かれたりしてて対応が難しそうな予感もします ![image](https://private-user-images.githubusercontent.com/61457993/317786948-0d5bd863-0b1f-499b-bee3-24e71914c84a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2OTcyNzcsIm5iZiI6MTcxMTY5Njk3NywicGF0aCI6Ii82MTQ1Nzk5My8zMTc3ODY5NDgtMGQ1YmQ4NjMtMGIxZi00OTliLWJlZTMtMjRlNzE5MTRjODRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDA3MjI1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmOTA1ZmIxM2RiNjBmZTZjNDE4YTA0OWVlZjAxNmY0OTg5Njc1NDFmZTI3YTM5Y2E3N2E4ZTkxZmQ3ODU2MDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7_5NYzhIGmNJawY7h2ByB-BUl4CNOSzNBL5r4U1CF_k)

修正チェックしましたが、boldじゃなくなってしまってそう…?

2024-03-29 07:33 UTC, Sayamame-beans requested changes

2024-03-29 07:33 UTC, Sayamame-beans commented on vrc-get-gui/locales/ja.json5
> +    "please select a file or folder": "ファイルまたはフォルダを選択してください",
```suggestion
    "please select a file or folder": "ファイルまたはフォルダを選択してください。",
```

2024-03-29 07:34 UTC, Sayamame-beans commented
647: 既存のはそのままになっている(DBに多分そのまま入っているので仕方無さそう)
646: 直っていない
644: 直ってそう?

644が直ってそうなおかげで気付きましたが、https://github.com/vrc-get/vrc-get/blob/9402ea26694a622565fcfb675ca3ef2c149a3581/vrc-get-gui/app/projects/page.tsx#L454 のテキストがjson側に無さそうなので足さないといけない

2024-03-29 07:38 UTC, Sayamame-beans commented
あれ? これって通常色でしたっけ…
![image](https://github.com/vrc-get/vrc-get/assets/61457993/a0f2dd28-b298-4f6d-bf2e-1bce24df613a)

2024-03-29 07:42 UTC, Sayamame-beans commented
プロジェクト作成時の空白末尾: 末尾の空白が無いものとして扱われるようになったことを確認しました。

なお、空白が複数ある場合に、表示上は1つになるようですが、これはこのままで大丈夫ですか? (作成されるフォルダ名は空白複数になっていたので、多分実害はそんなにないかと思います…?)
![image](https://github.com/vrc-get/vrc-get/assets/61457993/3af4562e-a621-4e8c-bafe-6560086325e2)

2024-03-29 07:50 UTC, Sayamame-beans commented
> テキストがjson側に無さそう
これさてはactionsとか欲しいやつですね…判断する術あるのかな(別issue立てますね)

2024-03-29 09:17 UTC, anatawa12 commented
> 647: 既存のはそのままになっている(DBに多分そのまま入っているので仕方無さそう)

とりあえず放置します

> 646: 直っていない

OS認識APIがなんか使えてなかった。直した

> あれ? これって通常色でしたっけ…

直した

> なお、空白が複数ある場合に、表示上は1つになるようですが、これはこのままで大丈夫ですか? 

直した

2024-03-29 09:52 UTC, Sayamame-beans commented
> > なお、空白が複数ある場合に、表示上は1つになるようですが、これはこのままで大丈夫ですか?

> 直した

この部分だけ直ってないみたいです(作成時のパスと、manageページのパス、プロジェクト名表記には問題ないことを確認しました)
![image](https://github.com/vrc-get/vrc-get/assets/61457993/e4c14e00-d1a9-48a7-a8b8-c22bcebdefd0)

2024-03-29 09:55 UTC, Sayamame-beans commented
これ以外だと、あとは https://github.com/vrc-get/vrc-get/pull/676#issuecomment-2026803635 だけですかね…? boldじゃなくなったやつ
![image](https://github.com/vrc-get/vrc-get/assets/61457993/2b4718b8-764c-4b81-a243-999c0437fb6d)

2024-03-29 10:06 UTC, anatawa12 commented
boldじゃない、再現できてない 
<img width="766" alt="image" src="https://github.com/vrc-get/vrc-get/assets/22656849/9d4b26a1-ec63-4dad-a820-897f9d959e7a">

2024-03-29 10:07 UTC, Sayamame-beans commented
えぇ…

2024-03-29 10:09 UTC, Sayamame-beans commented
フォントの都合とかなのかな

2024-03-29 10:11 UTC, Sayamame-beans commented
font-lightが入ってると太字にならないみたいですね

2024-03-29 10:12 UTC, Sayamame-beans commented
![image](https://github.com/vrc-get/vrc-get/assets/61457993/b24ff008-3adf-4f84-9f38-e02801a3a1f9)
SDK Worldsの方の表示から抜いてみた様子

2024-03-29 10:14 UTC, anatawa12 commented
`font-weight: bolder;`でもとよりboldしろと指示があるのに何故かそれが効かない

2024-03-29 10:18 UTC, anatawa12 commented
とりあえずウェイトをnormalにした

2024-03-29 10:19 UTC, Sayamame-beans commented
直った！
![image](https://github.com/vrc-get/vrc-get/assets/61457993/cf7a026a-513c-42bb-a6d3-44418c2822e4)

2024-03-29 10:19 UTC, Sayamame-beans commented
ところでウィンドウの幅が1320px超えるとダイアログ小さくなるのに気付いた…
謎
![image](https://github.com/vrc-get/vrc-get/assets/61457993/1c06fb39-f299-45f1-8981-be2bfcb70354)

2024-03-29 10:22 UTC, Sayamame-beans commented
現在の状況
![image](https://github.com/vrc-get/vrc-get/assets/61457993/432ca171-e6b9-48f4-86da-353406344e22)

2024-03-29 10:26 UTC, anatawa12 commented
> ところでウィンドウの幅が1320px超えるとダイアログ小さくなるのに気付いた…
謎

スタイルの細かいとこは一旦無視の方針なので放置

2024-03-29 10:27 UTC, anatawa12 commented
(パス名とかは情報が正しくないなので治す)

2024-03-29 10:35 UTC, Sayamame-beans commented
![image](https://github.com/vrc-get/vrc-get/assets/61457993/cc8c7ac7-9a83-4e6f-9bdf-dbc0c7e291da)
strongが効いてないです
多分さっきのboldと同じだと思います

2024-03-29 10:48 UTC, Sayamame-beans commented
トーストを太字に出来るべきか悩んでいます
(インストールしたパッケージ名の表示を太字にするかどうか)

2024-03-29 11:02 UTC, anatawa12 commented
デフォルトweightをnormalにしたので多分boldかかるようになった

2024-03-29 11:16 UTC, Sayamame-beans commented
おっと…

2024-03-29 11:21 UTC, Sayamame-beans commented
んー…
パッケージのところには掛かるようになりましたね
前述のstrongのところと、今足そうとしていた他の所(リポジトリ追加時のリポジトリ名)には作用しないように見えます(範囲外ですか?)
さっき使われてた`className={"font-normal"}`なら機能するのは確認しました(push直前だった)

2024-03-29 11:28 UTC, Sayamame-beans commented
とりあえず文章だけboldにしたやつをpushします
ちなみにURLの方はcodeにするか迷ってやってません(どっちでも良さそう…今はリポジトリ一覧の方でもplaintextっぽいので)

2024-03-29 11:37 UTC, Sayamame-beans commented on vrc-get-gui/app/projects/page.tsx
> +						<Typography className="font-normal whitespace-pre">
https://github.com/vrc-get/vrc-get/pull/676/commits/7a49e439f156af5efb7b4a35bef9af2cde120e25 を元に修正しました

2024-03-29 11:38 UTC, Sayamame-beans commented
> トーストを太字に出来るべきか悩んでいます (インストールしたパッケージ名の表示を太字にするかどうか)

ややこしそうなので今回は一旦保留とします
(追加した通知のトーストはそれほど重要じゃないでしょうし)

従って残りはboldだけです

2024-03-29 11:58 UTC, anatawa12 commented
ダイアログの該当テキストがTypographyになかったのでそうした

2024-03-29 12:27 UTC, Sayamame-beans commented
移行時に対応するUnityが無い場合に出てくるダイアログは手元で再現面倒なので避けました
リポジトリ追加の方: 駄目(font-normalになってないかも)
Strong: 駄目(font-normalになってないかも)
既存Unity追加: OK
非Unity追加: `io error: Unity exists with non zero value: exit code: 1`とか`io error: Unity exists with non zero value: exit code: 0xffffffff`とか出る

2024-03-29 12:31 UTC, anatawa12 commented
> Strong: 駄目(font-normalになってないかも)

はどこ？

2024-03-29 12:31 UTC, Sayamame-beans commented
> > Strong: 駄目(font-normalになってないかも)
> 
> はどこ？

プロジェクトを削除しようとした時に出るダイアログのプロジェクト名部分です

2024-03-29 12:41 UTC, Sayamame-beans commented
今気付いたのですが、ワールドプロジェクト(3.4.2, 3.5.2)においてUdonSharpが追加可能なパッケージとして表示されています
いつからのバグでしょう…?

2024-03-29 12:41 UTC, anatawa12 commented
> 今気付いたのですが、ワールドプロジェクト(3.4.2, 3.5.2)においてUdonSharpが追加可能なパッケージとして表示されています
いつからのバグでしょう…?

気にしてなかった

2024-03-29 12:43 UTC, Sayamame-beans commented
ClientSimとUdonSharpは3.4.0以降が入っているなら表示されないというのがVCCの挙動ですが、どうします…? 一覧には出しておいて、3.4.0以降が入っている場合は、互換性なし扱いの表示/ダイアログ表示にするとかの方がanatawaさん好みの挙動です?

2024-03-29 12:49 UTC, anatawa12 commented
入ってるやつのlegacy packagesは非表示にするのがまぁ妥当なのはそうなのでそうします

2024-03-29 12:49 UTC, anatawa12 commented
> プロジェクトを削除しようとした時に出るダイアログのプロジェクト名部分です

は謎だけど解決策がわからんのでfont-normalを追加します

2024-03-29 13:01 UTC, anatawa12 commented
多分ok

2024-03-29 13:13 UTC, Sayamame-beans commented
載せるとしたら、空白表示問題と、末尾空白問題と、Unity追加失敗問題と、レガシーパッケージ表示についての4つ?

2024-03-29 13:30 UTC, anatawa12 commented
レガシーが競合するのは直さないとですね。vpmなので両方に書く

2024-03-29 15:03 UTC, Sayamame-beans requested changes

2024-03-29 15:03 UTC, Sayamame-beans commented on CHANGELOG-gui.md
> +- We could not add a unity manually `#676`
```suggestion
- We could not add unity manually `#676`
```
付けるならanですが、まあ無くても良いかなって…

```suggestion
- We could not add an unity manually `#676`
```

2024-03-29 15:08 UTC, anatawa12 commented on CHANGELOG-gui.md
> +- We could not add a unity manually `#676`
調べた感じ半母音はaですねそして発音は /júːnəṭi/ で /j/ は半母音なので a で良さそう

2024-03-29 15:12 UTC, Sayamame-beans commented
並び順そうなるんだの顔してます(全く致命的ではない(全部読めば良いだけなので))
![image](https://github.com/vrc-get/vrc-get/assets/61457993/a2d710ff-49ac-42dc-9222-5ff9026df406)

2024-03-29 15:13 UTC, Sayamame-beans commented
ちなみに逆になったりもします
(きっとここの表示順は固定じゃないんでしょうね)

2024-03-29 15:15 UTC, anatawa12 commented
そこの並び順、何もルールがないので完全に不定ですね。hashmapなので

2024-03-29 15:17 UTC, Sayamame-beans approved these changes
気になるところはありますが、とりあえず自然言語的にはOKだと思います

2024-03-29 15:17 UTC, Sayamame-beans commented on vrc-get-gui/locales/en.json5
> +    "Removing the project...": "Removing the project...",
そういえばここ、キーが大文字になってますね(全体的に全部小文字だったはず…)

2024-03-29 15:19 UTC, Sayamame-beans commented
> そこの並び順、何もルールがないので完全に不定ですね。hashmapなので

何となく、非決定的な中でもインストールとアンインストールぐらいの単位では表示が分かれてると嬉しそうですが、私だけかもしれませんし、このPRの範疇でもなさそうかな

2024-03-29 15:31 UTC, Sayamame-beans commented
> 気になるところはありますが、とりあえず自然言語的にはOKだと思います

あー、boldになった項目増えてるから大丈夫じゃなかった

2024-03-29 15:34 UTC, anatawa12 commented on vrc-get-gui/locales/en.json5
> +    "Removing the project...": "Removing the project...",
小文字であるべきですね

2024-03-29 15:38 UTC, Sayamame-beans requested changes
last review

2024-03-29 15:38 UTC, Sayamame-beans commented on CHANGELOG-gui.md
> +- Package names on the Apply Changes dialog are now bold `#676`
```suggestion
- Package names on the Apply Changes dialog and a few other texts are now bold `#676`
```

2024-03-29 15:38 UTC, Sayamame-beans commented on vrc-get-gui/locales/en.json5
> +    "Removing the project...": "Removing the project...",
```suggestion
    "removing the project...": "Removing the project...",
```

2024-03-29 15:38 UTC, Sayamame-beans commented on vrc-get-gui/locales/ja.json5
> +    "Removing the project...": "プロジェクトを削除中...",
```suggestion
    "removing the project...": "プロジェクトを削除中...",
```

2024-03-29 15:38 UTC, Sayamame-beans commented on vrc-get-gui/lib/remove-project.tsx
> +						{tc("Removing the project...")}
```suggestion
						{tc("removing the project...")}
```

2024-03-29 15:43 UTC, anatawa12 commented on vrc-get-gui/locales/en.json5
> +    "Removing the project...": "Removing the project...",
別途変えちゃった

2024-03-29 15:50 UTC, Sayamame-beans approved these changes
LGTM! Really excellent work!

2024-03-29 15:58 UTC, merged