Unity management improvements
vrc-get/vrc-get pull request #863
Opened 2024-04-28 14:42 UTC by anatawa12

2024-05-02 20:39 UTC, Sayamame-beans requested changes
とりあえず
翻訳キーと動作確認は後ほど

2024-05-02 20:39 UTC, Sayamame-beans commented on CHANGELOG-gui.md
> +  - Currently, ALCOM will ask every time you open Unity. In the feature we will save the selection.
```suggestion
  - Currently, ALCOM will ask every time you open Unity. We will implement saving the selection in the future.
```

2024-05-03 08:09 UTC, Sayamame-beans commented on vrc-get-gui/locales/en.json5
バージョンが一致しない場合のダイアログが消えて、パッチバージョンが古い場合のダイアログだけ生えたように見えますが、多分3.6f1と3.22f1以外はサポートされていない(アップロードが反映されないかも)ので依然として必要そうとか、より新しいバージョン(3.27f1とか)の場合は表記が矛盾してしまいそうなどの考えが頭に浮かんでいます

2024-05-03 08:47 UTC, Sayamame-beans commented
`projects:manage:suggest unity patch migration`って未実装です…? (ベースを作っただけ?)

2024-05-03 09:21 UTC, anatawa12 commented on vrc-get-gui/locales/en.json5
より新しい場合の表記が矛盾してるのはそうなんですがそこまで細かく対応しないでいいだろうという判断です

2024-05-03 09:21 UTC, anatawa12 commented
> `projects:manage:suggest unity patch migration`って未実装です…? (ベースを作っただけ?)

部分的にいいえ。2022.3.2f1とかのプロジェクトを見ると 2022.3.6f1に上げるsuggestionがでます。

2024-05-03 10:13 UTC, Sayamame-beans commented
言われてみればそうでした

2024-05-03 10:15 UTC, Sayamame-beans commented
> `projects:manage:suggest unity patch migration`って未実装です…? (ベースを作っただけ?)

これ、あれですね…キーが使われてる場所がないのではという意図もあったのを思い出しました

2024-05-03 10:19 UTC, anatawa12 commented on vrc-get-gui/app/projects/manage/page.tsx
> +				{tc("projects:manage:suggest unity patch migration")}
キーはここで使ってる

2024-05-03 10:20 UTC, Sayamame-beans commented on vrc-get-gui/app/projects/manage/page.tsx
> +				{tc("projects:manage:suggest unity patch migration")}
diff読み込まれてなかったやつでした…失礼

2024-05-04 09:40 UTC, Sayamame-beans requested changes
日本語は別PRで生やそうかなと考えていたり(ここでやった方が良ければやります)

2024-05-04 09:40 UTC, Sayamame-beans commented on vrc-get-gui/locales/en.json5
> +    "projects:manage:dialog:exact version unity not found for patch migration description": "We could not find exact recommended version of Unity 2022 for patch migration.<br>Please install Unity {{u
ここでは"Unity {{unity}}"で、上では{{unity}}だけなのが若干気になりました

2024-05-04 09:40 UTC, Sayamame-beans commented on vrc-get-gui/locales/en.json5
> +    "projects:manage:dialog:exact version unity not found for patch migration description": "We could not find exact recommended version of Unity 2022 for patch migration.<br>Please install Unity {{u
(あと、(元からですが)キーが長いのが少し気になったんですが、代わりの案が思いついていません)

2024-05-04 10:07 UTC, anatawa12 commented
日本語は別PRのつもりです

2024-05-04 10:22 UTC, anatawa12 commented on vrc-get-gui/locales/en.json5
> +    "projects:manage:dialog:exact version unity not found for patch migration description": "We could not find exact recommended version of Unity 2022 for patch migration.<br>Please install Unity {{u
キーの長さはどうしょうもない気がする

前者はUnity {{unity}}にします

2024-05-05 05:22 UTC, Sayamame-beans approved these changes
maybe ok

2024-05-05 05:27 UTC, merged