Docs contributing guide link
vrc-get/vrc-get pull request #906
Opened 2024-05-04 17:34 UTC by Misaka-L

Since many tanslator report (to me) that.... they can't find the way to solve the symlinks and git submoduels problem. (because they didn't find that there was a CONTRIBUTING.md file....)

I made a pull request to add CONTRIBUTING.md link to each README.md. And update the root CONTRIBUTING.md file clone command to make sure that, symlinks is create correctly (instead of a plain text file with file path)

2024-05-04 18:08 UTC, anatawa12 requested changes
Thank you for suggestion!

Adding link to contributing.md is good!

However, I don't like to add core.symlink=true because it's very environment specific.

2024-05-04 18:12 UTC, Misaka-L commented on CONTRIBUTING.md
> +git clone --recurse-submodules -c core.symlinks=true https://github.com/vrc-get/vrc-get.git
I removed it. and think maybe we can add a single command to tell user how to enable symlinks support for their git?

2024-05-04 18:17 UTC, anatawa12 approved these changes
LGTM! Thank you!

2024-05-04 18:37 UTC, merged

2024-05-05 05:04 UTC, anatawa12 commented on CONTRIBUTING.md
> +git clone --recurse-submodules -c core.symlinks=true https://github.com/vrc-get/vrc-get.git
Sorry I didn't notice the comment  in the resolved thread.

I don't think adding core.symlink=true is the best way to enable symlink and the link above describes correct way to enable symlink and workaround with copying files (per repository core.symlink)

2024-05-05 05:13 UTC, Misaka-L commented on CONTRIBUTING.md
> +git clone --recurse-submodules -c core.symlinks=true https://github.com/vrc-get/vrc-get.git
> Sorry I didn't notice the comment in the resolved thread.
> 
> I don't think adding core.symlink=true is the best way to enable symlink and the link above describes correct way to enable symlink and workaround with copying files (per repository core.symlink)

After some researches... I think add a link to a wiki article is a better solution due to Windows has a bad symlink support.