feat(gui): localized with crowdin
vrc-get/vrc-get pull request #949
Opened 2024-05-11 17:36 UTC by Misaka-L

NOTE: it shouldn't be merged directly since it need a crowdin project ID (https://github.com/Misaka-L/vrc-get/blob/b2901d13b729a0e0f71706930312d9ce2374b957/vrc-get-gui/public/crowdin-in-context.js#L2)

#948

2024-05-12 05:08 UTC, anatawa12 commented
To avoid merging by mistake, I make this pr as draft.

2024-05-12 06:46 UTC, anatawa12 requested changes
Thank you for suggestion.

However, I think it's important to keep author information in git history and as far as I found it couldn't with crowdin.
Unless we found some solution for git author problem, I don't like to use crowdin.

https://github.com/vrc-get/vrc-get/issues/948#issuecomment-2106120758

2024-05-12 07:02 UTC, Misaka-L commented on vrc-get-gui/locales/de.json
> +  }
solved by using (https://store.crowdin.com/jsonc)

2024-05-12 07:09 UTC, Misaka-L commented on vrc-get-gui/locales/de.json
> +  }
maybe need some work to let `json5` work in crowdin.

2024-05-12 07:09 UTC, Misaka-L commented on vrc-get-gui/src/commands.rs
> +                url.scheme() == "tauri" || (url.scheme() == "https" && url.host_str() == Some("accounts.crowdin.com"))
solved in https://github.com/vrc-get/vrc-get/pull/949/commits/e869bf4c5ae6cc472c45be5dd59aa49e60a15b94

2024-05-12 07:17 UTC, Misaka-L commented on vrc-get-gui/locales/de.json
> +  }
I think it is possible to download the `json` file from Crowdin and convert it into a `json5` file using a GitHub Action workflow. Additionally, we can create a workflow that converts the source file from `json5` to `json` and then uploads it to Crowdin.

2024-05-12 07:22 UTC, anatawa12 commented on vrc-get-gui/locales/de.json
> +  }
umm... is there any format without trailing comma problem that crowdin supports? changing format might be better fix

2024-05-12 07:28 UTC, Misaka-L commented on vrc-get-gui/locales/de.json
> +  }
> umm... is there any format without trailing comma problem that crowdin supports? changing format might be better fix

maybe [toml](https://store.crowdin.com/toml) or [yaml](https://store.crowdin.com/yaml) even xml?

2024-05-13 01:18 UTC, anatawa12 commented
https://github.com/vrc-get/vrc-get/issues/948#issuecomment-2106460897

2024-05-13 01:18 UTC, closed without merging